### ISSUE TITLE
browse.cc:1:0: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by 503612068** [rbgirshick/rcnn#85]
Hi @rbgirshick ,
When I compiled ninja  with ./configure.py an error report.....(enviroment:linux aarch64,python2.7)
pi@raspberrypi:~/ninja$ ./configure.py --bootstrap
bootstrapping ninja...
./src/browse.cc:1:0: internal compiler error: Segmentation fault
 // Copyright 2011 Google Inc. All Rights Reserved.
 
g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
when running:  g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python"' -O2 -DNDEBUG -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o
Traceback (most recent call last):
  File "./configure.py", line 456, in <module>
    objs += cxx('browse', order_only=built('browse_py.h'))
  File "./configure.py", line 282, in cxx
    return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
  File "./configure.py", line 164, in build
    self._run_command(self._expand(cmd, local_vars))
  File "./configure.py", line 189, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python"' -O2 -DNDEBUG -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o' returned non-zero exit status 4

**Comment by 503612068** [comment]
I also used python3.5,the error is still occured.

**Comment by 503612068** [comment]
Lastly,i found my gcc version was 6.3.I downgraded it to 4.9.2.The error was fixed.I think gcc-4.9.2 isn't supported by most os in the fulture,right?
